apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaopeso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peso
  template:
    metadata:
      labels:
        app: peso
    spec:
      containers:
        - name: peso
          image: gabriel0029/conversao-peso:1.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: peso
spec:
  selector:
    app: peso
  ports:
    - port: 80
      nodePort: 30001
  type: NodePort
